spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hashtag
    driver-class-name: org.mariadb.jdbc.Driver
    username: hashtag
    password: hashtag11
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update