spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hashtag
    username: hashtag
    password: hashtag11

  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: create # db 컬럼과 일치하는지 확인
    properties:
      hibernate:
        format_sql: true # 로그 출력
        show_sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG