spring:
  profiles:
    include: "gcp"
  datasource:
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true

jwt :
  secret : hellymkimmijinbekedehdgoanfrhkqorentksdlakfmrhekfgehfhrgksmsmsladlgksmslsadlqhdngkekdnflskfkakstp